#!/bin/bash

WIN_ID=$(xdotool getactivewindow)

if [[ $1 != "dec"  ]] ;
then
	xprop -id $WIN_ID -f _MOTIF_WM_HINTS 32c -set	_MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0" &
else
	xprop -id $WIN_ID -f _MOTIF_WM_HINTS 32c -set	_MOTIF_WM_HINTS "0x2, 0x0, 0x1, 0x0, 0x0" &
fi

xdotool windowactivate $WIN_ID
